<?xml version="1.0" encoding="utf-8"?><Database Name="nssnc" Class="ARSTempDataContext" xmlns="http://schemas.microsoft.com/linqtosql/dbml/2007">
  <Connection Mode="AppSettings" ConnectionString="Data Source=JOSEPH\SQLEXPRESS;Initial Catalog=nssnc;Integrated Security=True" SettingsObjectName="UpdateNeuseInventory.Properties.Settings" SettingsPropertyName="nssncConnectionString" Provider="System.Data.SqlClient" />
  <Table Name="dbo.NeuseARSTemp" Member="NeuseARSTemps">
    <Type Name="NeuseARSTemp">
      <Column Name="upc" Type="System.String" DbType="NVarChar(MAX)" CanBeNull="true" />
      <Column Name="qty" Type="System.Decimal" DbType="Decimal(18,4)" CanBeNull="true" />
    </Type>
  </Table>
</Database>